#! /bin/sh
set -xeuf

test -f src

if test -f src.mime-type; then
  type="`cat src.mime-type`"
else
  type="`file -ib src`"
fi

length=`wc -c src | awk '{print$1}'`

cat<<EOF
HTTP/1.1 200 OK
Content-Type: $type
Content-Length: $length${TEXT_filename+
Content-Disposition: attachment; filename=$TEXT_filename}
Connection: close

EOF

dd if=src bs=$length
