#! /bin/sh
set -xeuf

mkdir -p tmp

cd src

# remove any potential build directory
rm -fR build

if ! test -e frameworks; then
  mkdir frameworks
  ln -s /more/mway/Espresso/frameworks/The-M-Project frameworks
fi

/more/mway/Espresso/bin/espresso.js build

# Note: we know there can only one directory in build/!
name="`cd build && ls`"

# replace src with the build 
mv build/$name ../tmp
cd ..
rm -fR src
mv tmp/$name src
